include/secp256k1_whitelist.h
src/modules/whitelist/main_impl.h
src/modules/whitelist/tests_impl.h

Fixes #9 
Interestingly, documentation for the n_keys argument was already present. Commit also adds a test.

Add n_keys argument to whitelist_verify

---

src/modules/whitelist/Makefile.am.include

should fix `make distcheck` when module enabled.

add whitelist_impl.h to include for dist

---

src/modules/generator/main_impl.h

I stumbled across this when I compiled secp256k1 for C++. Easiest fix is to change length to 17.
The alternative is to use { ... } syntax for C data initialization.

Minor bugfix. Wrong length due to NUL character.

---

include/secp256k1_rangeproof.h

Was failing linking to `*.so` library

Expose generator in shared library

---

src/modules/generator/main_impl.h
src/modules/generator/tests_impl.h

generator: remove `CHECK` abort calls exposed by public API

---

include/secp256k1_generator.h

It should be named `gen` (instead of `commit`).

Fix a small typo in the generator parameter name

---

Makefile.am

port of https://github.com/bitcoin-core/secp256k1/pull/597, this is necessary to run the tests on ARM

Add $(COMMON_LIB) to exhaustive tests to fix ARM asm build

---

src/asm/field_10x26_arm.s

port of https://github.com/bitcoin-core/secp256k1/pull/612/

Allow field_10x26_arm.s to compile for ARMv7 architecture

---

src/modules/rangeproof/main_impl.h

I'm suggesting to link to this procedure from the taproot BIP (https://github.com/sipa/bips/pull/43) to create a internal taproot key without known dlog. Importing hashlib and defining F are necessary to just copy and paste and run this.

Clarify how to derive alternative generator H

---

src/modules/whitelist/whitelist.md

The "garbage key" does not result in burned coins if attacker and participant cooperate.

Improve explanation of key cancellation attack in whitelist.md

---

include/secp256k1_surjectionproof.h
src/modules/surjection/main_impl.h
src/modules/surjection/tests_impl.h

Relevant issue: #36 
This is working, but not yet finished. I am asking for review and  comments.
In particular, I am not sure about naming for the functions.
naming allocation function `secp256k1_surjectionproof_create`, to be in line with the `secp256k1_scratch_space_create`, have a problem that this might get confused with `secp256k1_surjectionproof_generate` - completely different function, but the meanings for the words 'create' and 'generate' are close.
I decided to use the name `secp256k1_surjectionproof_allocate_initialized` - literally what the function would do.
At the same time, for the deallocation function, I used 'destroy' (`secp256k1_surjectionproof_destroy`), because it is used for this meaning in other places.
Other concern what I want to request comments on, is that …

add allocate/destroy functions for secp256k1_surjectionproof

---

src/modules/surjection/main_impl.h

Improve comments for surctionproof init+alloc/destroy funcs
The comments with 'XXX' was intended to indicate that the listed
concerns was subject to review and change, but the code with these
comments was merged straight away. This commit replaces comments
with more complete text describing the issues.
This also signifies that the commit that this code was introduced in is
not anymore 'work in progress'.

Improve comments for surctionproof init+alloc/destroy funcs

---

configure.ac
include/secp256k1_surjectionproof.h
src/modules/surjection/main_impl.h
src/modules/surjection/surjection_impl.h
src/modules/surjection/tests_impl.h

This would be a softfork of Elements. Alternately we could make this constant settable at compile time for limited-memory wallets.

surjectionproof: reduce stack usage and limit proofs to anonymity set of 16

---

include/secp256k1_musig.h
src/modules/musig/example.c
src/modules/musig/main_impl.h
src/modules/musig/tests_impl.h

With this PR it's possible to create MuSig signatures for public keys with pay to contract commitments:
```
secp256k1_musig_pubkey_combine(.., &P, pk_hash, pk, ...);
secp256k1_ec_pubkey_tweak_add(ctx, &Q, ec_commit_tweak);
/* Note same pk_hash as in pubkey combine but with tweaked key Q */
secp256k1_musig_session_initialize(..., &Q, pk_hash, ...);
...
secp256k1_musig_partial_sig_combine(..., ec_commit_tweak);
```
If the signers want to create a signature for the the normal combined key `P` they run the protocol just as before (i.e. initialize the session with `P` and give `NULL` to the `partial_sig_combine` `tweak32` argument.

Add tweak32 parameter to musig_partial_sig_combine

---

src/java/org/bitcoin/NativeSecp256k1Test.java

This removes a dependency on javax.xml.bind, which is no longer
available in JDK >= 11, see
https://openjdk.java.net/jeps/320#Java-EE-modules .
This fixes Travis, whose Java builds were failing recently.

port of secp256k1#566 "jni: Use only Guava for hex encoding and decoding"

---

include/secp256k1_musig.h
src/modules/musig/example.c
src/modules/musig/main_impl.h
src/modules/musig/musig.md
src/modules/musig/tests_impl.h

This PR removes the `set_msg` function from the musig module and adds a `msg` argument `get_public_nonce` which must be non-null if the message has not been set during initialization.
The reason for this is that I think that our current `set_msg` logic is vulnerable to Wagner's attack. The main problem is that by grinding the message an attacker has control over the final hash being signed.
Assume the combined pubkey of Alice and the attacker is `P`.
The attacker wants to forge a signature on message `m'` and opens 3 parallel sessions with Alice.
They exchange nonce commitments and nonces.
Let's call the combined nonces `Ri` for sessions `i = 0,1,2`.
Now the attacker draws `ka` and sets `R' = R0 + R1 + R2 + ka*G` and runs Wagner's algorithm grinding `mi` to find
```
H(P, R',m') = H(P, R1, …
```

 Require message in musig protocol in an earlier state

---

contrib/travis.sh
src/ecmult_const_impl.h
src/group.h
src/group_impl.h
src/scalar_4x64_impl.h
src/scalar_8x32_impl.h
src/tests.c
src/tests_exhaustive.c
src/util.h

[upstream PR #772]: Improve constant-timeness on PowerPC
[upstream PR #779]: travis: Fix argument quoting for ./configure
[upstream PR #778]: secp256k1_gej_double_nonzero supports infinity
Created using a new version of #98. Could have done more than 3 commits but wanted to show how this looks like first. By the way `git rerere` is really useful for doing these kind of merges because it remembers how you resolved merge conflicts.

Upstream PRs  #772 #779 #778

---

include/secp256k1_rangeproof.h

Remove unused context initializer functions

---

.travis.yml
include/secp256k1_musig.h
src/modules/musig/example.c
src/modules/musig/main_impl.h
src/modules/musig/musig.md
src/modules/musig/tests_impl.h

This PR is mainly a rebase of #87. It also adds taproot tweaking which was part of #86 but then got lost. The PR has a few changes that are seem unnecessary if we upgrade to MuSig2 soon, but overall I think they'll make that switch easier.

MuSig state machine simplifictions, API improvements and taproot tweaking

---

src/modules/rangeproof/tests_impl.h
src/modules/surjection/tests_impl.h

This, along with setting the test count to 32 rather than 64, reduces the default test run from 1m40 on my laptop to 30s.

reduce test rounds for rangeproof and surjectionproof

---

include/secp256k1_rangeproof.h

Found this note on this in @thomaseizinger's rust-secp256k1-zkp:
```
// TODO: File bug with upstream: message length is not set correctly
```
The message length is okay but this is a doc bug.

rangeproof: clarify rewind outlen argument

---

include/secp256k1_generator.h

I don't know what users usually prefer, `key32` or `seed32`. But, at least the naming should be consistent.

Make function argument name consistent with doc

---

.cirrus.yml
Makefile.am
README.md
ci/cirrus.sh
configure.ac
include/secp256k1_ecdsa_adaptor.h
src/modules/ecdsa_adaptor/Makefile.am.include
src/modules/ecdsa_adaptor/dleq_impl.h
src/modules/ecdsa_adaptor/main_impl.h
src/modules/ecdsa_adaptor/tests_impl.h
src/secp256k1.c
src/tests.c
src/valgrind_ctime_test.c

This PR adds support for ECDSA adaptor signatures. It is based on the work of @jonasnick in https://github.com/jonasnick/secp256k1/pull/14.
This implementation conforms to the [DLC specification](https://github.com/discreetlogcontracts/dlcspecs/pull/114) and includes test vectors from the specification.
The specification is based on the [paper](https://github.com/LLFourn/one-time-VES/blob/master/main.pdf) "One-Time Verifiably Encrypted Signatures A.K.A. Adaptor Signatures" by @LLFourn. The idea was first proposed in a lightning-dev [post](https://lists.linuxfoundation.org/pipermail/lightning-dev/2019-November/002316.html).
I've [implemented](https://github.com/jesseposner/dlc/blob/master/ecdsa_adaptor.py) the specification in Python as well, which can be useful for testing purposes. …

Add ECDSA adaptor signatures module

---

contrib/sync-upstream.sh

Try
`git --no-pager log --oneline upstream/master --merges 4c3ba88c3a869ae3f45990286c79860539a5bff8..1758a92f`
vs
`git --no-pager log --oneline --merges 4c3ba88c3a869ae3f45990286c79860539a5bff8..1758a92f`.

sync-upstream: fix "end" parameter for specifying range

---

src/modules/rangeproof/main_impl.h

The warning is:
```
In file included from src/scalar_impl.h:22,
from src/secp256k1.c:14,
from src/tests_exhaustive.c:26:
src/modules/rangeproof/main_impl.h: In function ‘secp256k1_pedersen_blind_generator_blind_sum’:
src/scalar_low_impl.h:36:20: warning: ‘tmp’ may be used uninitialized in this function [-Wmaybe-uninitialized]
36 |     *r = (*a + *b) % EXHAUSTIVE_TEST_ORDER;
In file included from src/secp256k1.c:847,
from src/tests_exhaustive.c:26:
src/modules/rangeproof/main_impl.h:170:22: note: ‘tmp’ was declared here
170 |     secp256k1_scalar tmp;
|                      ^~~
```
GCC 11.1.0
(Note that the location is a little strange because the `scalar_add` from `scalar_low_impl.h` has been inlined.)

Eliminate a wrong -Wmaybe-uninitialized warning in GCC

---

.cirrus.yml
.gitignore
Makefile.am
README.md
build-aux/m4/bitcoin_secp.m4
ci/linux-debian.Dockerfile
configure.ac
contrib/lax_der_parsing.c
contrib/lax_der_privatekey_parsing.c
include/secp256k1.h
include/secp256k1_schnorrsig.h
src/bench_schnorrsig.c
src/ecdsa_impl.h
src/ecmult.h
src/ecmult_gen.h
src/gen_context.c
src/modules/musig/example.c
src/modules/musig/tests_impl.h
src/modules/rangeproof/rangeproof_impl.h
src/modules/schnorrsig/main_impl.h
src/modules/schnorrsig/tests_exhaustive_impl.h
src/modules/schnorrsig/tests_impl.h
src/secp256k1.c
src/tests.c
src/tests_exhaustive.c
src/valgrind_ctime_test.c

[bitcoin-core/secp256k1#879]: Avoid passing out-of-bound pointers to 0-size memcpy
[bitcoin-core/secp256k1#959]: tests: really test the non-var scalar inverse
[bitcoin-core/secp256k1#955]: Add random field multiply/square tests
[bitcoin-core/secp256k1#944]: Various improvements related to CFLAGS
[bitcoin-core/secp256k1#951]: configure: replace AC_PATH_PROG to AC_CHECK_PROG
[bitcoin-core/secp256k1#960]: tests_exhaustive: check the result of secp256k1_ecdsa_sign
[bitcoin-core/secp256k1#844]: schnorrsig API overhaul
[bitcoin-core/secp256k1#963]: "Schnorrsig API overhaul" fixups
[bitcoin-core/secp256k1#965]: gen_context: Don't use any ASM
This PR can be recreated  with `./contrib/sync-upstream.sh range be8d9c262f46309d9b4165b0498b71d704aba8fe`.

Upstream PRs 879, 959, 955, 944, 951, 960, 844, 963, 965

---

include/secp256k1_musig.h

musig: fix session_init argument NULL check

---

contrib/sync-upstream.sh

Otherwise strings in $TITLE and $BODAY that are enclosed in ` are executed in
gh-pr-create.sh.

sync-upstream: fix quoting

---

include/secp256k1_whitelist.h
src/bench_whitelist.c
src/modules/whitelist/main_impl.h
src/modules/whitelist/tests_impl.h

This functionality is inappropriate to expose for a zero-knowledge proof, and was confusingly (and potentially dangerously) implemented.
For now just replace it with code that uses the default ECDSA 6979 nonce, which we at least know will do something safe with the input that this code gives it (a "message" which is a commitment to all the pubkeys involved, xor'd with the index of which `s` value we are generating, alongside the secret key and a retry count in case of overflow). In a later PR I will just replace this mess with a sanely-seeded chacha.
(Ideally in future we would be using [Merlin](https://medium.com/@hdevalence/merlin-flexible-composable-transcripts-for-zero-knowledge-proofs-28d9fda22d9a) or something but for this borderline-legacy code I think it's best not to try anything …

whitelist: remove ability to specific nonce function

---

examples/musig.c
include/secp256k1_musig.h
src/modules/musig/keyagg_impl.h
src/modules/musig/session_impl.h
src/modules/musig/tests_impl.h

In short, `musig_pubkey_tweak_add` now allows for xonly _and_ "ordinary" tweaking. Also, in order to allow using `ec_pubkey_tweak_add` on the non-xonly aggregate public key, there's a new function `musig_pubkey_get` that allows obtaining it from the `keyagg_cache`.
One alternative would be that instead of adding `musig_pubkey_get`, we could change `pubkey_agg` to output an ordinary (non-xonly) pubkey. Then users of the API who do not need ordinary (BIP32) tweaking would be forced to call `xonly_pubkey_from_pubkey`. And we'd probably want to change the spec. And it would be a bit weird to output a pubkey that can't be directly schnorrsig_verify'd.
Based on #131

MuSig: Add Minimal Compatibility with BIP32 Tweaking

---

doc/musig-spec.mediawiki
src/modules/musig/keyagg.h
src/modules/musig/keyagg_impl.h
src/modules/musig/session_impl.h
src/modules/musig/tests_impl.h

~~This is a draft because I still need to add some comment to the implementation that explains how exactly we make `tweak` identical to `t` in `tweak_add`.~~
Based on #171

Add ordinary and x-only tweaking to spec and simplify implementation

---

configure.ac

Undeclared functions are fine in C but linking will fail.
This is a quick fix. In the long-term we should probably resort to `#ifdef`s as common in upstream.

configure: Check compile+link when checking existence of functions

---

doc/musig-spec.mediawiki

- KeyAggCoeff' -> KeyAggCoeffInternal for consistency
- In Sign, add mod n when calculating d
- In Tweak, reorder the parameters to (Q, gacc, tacc, tweak, is_xonly) because
the first three are "state" arguments
- Rename Tweak function to ApplyTweak to avoid confusion with tweak (the
vector). This becomes apparent in the python reference code.

musig-spec: address robot-dreams' comments

---

src/modules/extrakeys/hsort_impl.h

OpenBSD defines swap64 in <endian.h>.

extrakeys: rename swap/swap64 to fix OpenBSD 7.1 compilation

---

src/modules/surjection/main_impl.h
src/modules/surjection/tests_impl.h

If any ephemeral input tag equals the ephemeral output tag (i.e. an input asset is exactly equal to the output asset), verification will fail due to an unexpected interaction between our surjectionproof logic and the underlying borromean ring siganture logic. However, our generation code still allows creating proofs like this, "succeeding" in creating bad proofs.
Since we cannot fix the verification side without hardforking Liquid, fix the generation side to fail in this situation.

surjectionproof: fail to generate proofs when an input equals the output

---

src/modules/ecdsa_adaptor/main_impl.h
src/modules/ecdsa_adaptor/tests_impl.h
src/modules/ecdsa_s2c/main_impl.h
src/modules/ecdsa_s2c/tests_impl.h
src/modules/generator/main_impl.h
src/modules/generator/tests_impl.h
src/modules/rangeproof/borromean.h
src/modules/rangeproof/borromean_impl.h
src/modules/rangeproof/main_impl.h
src/modules/rangeproof/pedersen.h
src/modules/rangeproof/pedersen_impl.h
src/modules/rangeproof/rangeproof.h
src/modules/rangeproof/rangeproof_impl.h
src/modules/rangeproof/tests_impl.h
src/modules/surjection/main_impl.h
src/modules/surjection/surjection.h
src/modules/surjection/surjection_impl.h
src/modules/surjection/tests_impl.h
src/modules/whitelist/main_impl.h
src/modules/whitelist/tests_impl.h

This is causing out-of-tree build failures in Elements.

fix include paths in all the -zkp modules

---

include/secp256k1_rangeproof.h
src/modules/ecdsa_s2c/tests_impl.h
src/modules/generator/tests_impl.h
src/modules/musig/tests_impl.h
src/modules/rangeproof/borromean_impl.h
src/modules/rangeproof/rangeproof_impl.h
src/modules/rangeproof/tests_impl.h
src/modules/surjection/main_impl.h

I was curious about under what conditions you can create a rangeproof on an "unblinded" commitment which has a zero blinding factor. Apparently the answer is "when you are proving at least 3-bits". In this case rewinding words and you can encode 32 bytes of data. (In fact I believe you can encode up to 128 but I haven't tested that.)

rangeproof: add a test for all-zero blinding factors

---

src/modules/surjection/main_impl.h
src/modules/surjection/tests_impl.h

If the proof was generated with surjectionproof_initialize (as mandated by the
API docs), then n_used_pubkeys can never be 0. Without this commit, compilers
will (rightfully) warn that borromean_s[ring_input_index] is not initialized in
surjectionproof_generate. Therefore, this commit makes sure that n_used_pubkeys
is greater than 0 which ensures that the array is initialized at
ring_input_index.

surjectionproof: make sure that n_used_pubkeys > 0 in generate

---

src/modules/musig/musig.md

- the doc refers to `secp256k1_musig_pubkey_tweak_add` which doesn't exist: https://github.com/ElementsProject/secp256k1-zkp/commit/b7607f93f23a1a342b4fba552598e2a578f50527
- the doc incorrectly states that step 6 `nonce_process` can happen before the message to be signed is known, and before the aggregate key is known: https://github.com/ElementsProject/secp256k1-zkp/commit/d26100cab266b08fd131503ba8e37d9bf091adbb
- the doc omits tweak instructions for ordinary keys: https://github.com/ElementsProject/secp256k1-zkp/commit/dd83e72d52da0873e0c1a64c5554efa9000a3454

MuSig doc fixes

---

include/secp256k1_musig.h
src/modules/musig/session_impl.h
src/modules/musig/tests_impl.h

Builds on #211.
This PR implements a defense-in-depth measure that is specified in BIP-MuSig2. In fact, it revealed a bug in the `scriptless_atomic_swap` test.

musig: include pubkey in secnonce and compare when signing

---

contrib/sync-upstream.sh

This makes it possible to use sync-upstream with uncommitted changes. (This is in particular helpful when working on the script itself.)
Without this commit, git pull will fail due to the uncommitted changes.

sync-upstream: Use --autostash to handle uncommitted changes

---

src/modules/bppp/bppp_norm_product_impl.h
src/modules/bppp/tests_impl.h

bppp: align terminology with paper

---

include/secp256k1_extrakeys.h
src/modules/musig/keyagg_impl.h

https://github.com/BlockstreamResearch/secp256k1-zkp/pull/211#discussion_r1123162883
https://github.com/BlockstreamResearch/secp256k1-zkp/pull/211#discussion_r1123169094

musig: Fix nits left open in #211

---

.cirrus.yml
build-aux/m4/bitcoin_secp.m4
ci/cirrus.sh
ci/linux-debian.Dockerfile
configure.ac
include/secp256k1.h
sage/prove_group_implementations.sage
src/bench.h
src/bench_internal.c
src/group.h
src/group_impl.h
src/modules/schnorrsig/bench_impl.h
src/scratch_impl.h
src/secp256k1.c

[bitcoin-core/secp256k1#1056]: Save negations in var-time group addition
[bitcoin-core/secp256k1#1104]: Fix the false positive of `SECP_64BIT_ASM_CHECK`
[bitcoin-core/secp256k1#1105]: Don'\''t export symbols in static libraries
[bitcoin-core/secp256k1#1084]: ci: Add MSVC builds
[bitcoin-core/secp256k1#1114]: `_scratch_destroy`: move `VERIFY_CHECK` after invalid scrach space check
[bitcoin-core/secp256k1#1115]: Fix sepc256k1 -> secp256k1 typo in group.h
This PR can be recreated with `./contrib/sync-upstream.sh range 43756da819a235d813e7ecd53eae6df073b53247`.

Upstream PRs 1056, 1104, 1105, 1084, 1114, 1115

---

.cirrus.yml

See the failure here:
https://github.com/BlockstreamResearch/secp256k1-zkp/pull/249/checks?check_run_id=15209841852
I suggest merging this PR and then rebasing sync-upstream on master (and then #249 on sync-upstream). This will give us a bit more meaningful CI output for now when working on sync-upstream, even though the Linux tasks still don't work.

ci: Always define EXPERIMENTAL variable

---

src/modules/bppp/tests_impl.h

The test is supposed to create an invalid sign byte. Before this PR, the generated sign byte could in fact be valid due to an overflow.

bppp: Fix and improve test for invalid sign byte

---

contrib/musig2-vectors.py

The linter included in the Bitcoin Core and Elements test framework requires python3.

musig: change test vector generation code shebang from python to python3

---

src/modules/bppp/tests_impl.h

The first byte provided to secp256k1_bppp_parse_one_of_points is allowed to be 0, 1, 2, or 3 since it encodes the Y coordinate of two points. In a previous fix we wrongly assumed it can only be 2 or 3.

bppp: Fix test for invalid sign byte again

---

src/modules/surjection/main_impl.h

Following the merge of b627ba7050b608e869515a8ef622d71bf8c13b54 from upstream, this include should have been deleted as well.

surjectionproof: remove unused include

---

.github/workflows/ci.yml
Makefile.am
ci/ci.sh
configure.ac
include/secp256k1_schnorrsig_halfagg.h
src/modules/schnorrsig_halfagg/Makefile.am.include
src/modules/schnorrsig_halfagg/main_impl.h
src/modules/schnorrsig_halfagg/tests_impl.h
src/secp256k1.c
src/tests.c

Revisited PR #130 by jonasnick.
I am happy to hear your thoughts.
**Summary of changes compared to #130:** 
- Address comments from rustyrussell 
- Use tagged hash
- Compute hashes with common prefix by copying midstate
- Allow Incremental Aggregation and make code consistent with the [draft spec](https://github.com/BlockstreamResearch/cross-input-aggregation/blob/master/half-aggregation.mediawiki)

Schnorr (Incremental) Half Aggregation 

---

src/modules/generator/main_impl.h

The line calculating H (in particular, the expression `G.decode('hex')`) fails with the following error message on Sage 9.5:
```
AttributeError: 'str' object has no attribute 'decode'
```
Fix that by converting the hex-string to bytes using `bytes.fromhex`.
(Noticed while reviewing https://github.com/bitcoin/bitcoin/pull/30048 which picks this code snippet comment up.)

doc: fix sage code for deriving alternative generator H

---

src/modules/generator/main_impl.h
src/modules/generator/tests_impl.h

`secp256k1_pedersen_commit_serialize` would call `_load` (which does a sqrt to fully decompress the key, then a conditional negation based on the flag), then check the Jacobian symbol of the resulting y-coordinate, then re-serialize based on this.
Instead, don't do any of this stuff. Copy the flag directly out of the internal representation and copy the x-coordinate directly out of the internal representation.
Checked that none of the other _serialize methods in the modules do this.
Fixes #293

generator: massively speed up serialization

---

src/modules/rangeproof/tests_impl.h

I was a bit confused reading `secp256k1_rangeproof_getheader_impl` because in the case of single-value proofs (`has_nz_range == 0`) some bits of the header are unconstrained. At first I thought this was a malleability vector. And I think I've had this same confusion in the past.
But in fact it is not a malleability vector because the whole header gets hashed into the proof.
Add a unit test to confirm this to reduce future confusion.

rangeproof: add unit test for malleating single-value proofs
